-- Clear existing data and add comprehensive Parts of Speech questions with mixed incorrect options
DELETE FROM grammar_runner_parts_of_speech_questions;

INSERT INTO grammar_runner_parts_of_speech_questions (question, incorrect, correct, explanation) VALUES
-- NOUNS (person, place, thing, idea) - mixed incorrect options
('book', 'verb', 'noun', 'Book is a person, place, or thing, so it''s a noun'),
('house', 'adjective', 'noun', 'House is a person, place, or thing, so it''s a noun'),
('car', 'adverb', 'noun', 'Car is a person, place, or thing, so it''s a noun'),
('tree', 'verb', 'noun', 'Tree is a person, place, or thing, so it''s a noun'),
('computer', 'adjective', 'noun', 'Computer is a person, place, or thing, so it''s a noun'),
('phone', 'verb', 'noun', 'Phone is a person, place, or thing, so it''s a noun'),
('table', 'adverb', 'noun', 'Table is a person, place, or thing, so it''s a noun'),
('chair', 'adjective', 'noun', 'Chair is a person, place, or thing, so it''s a noun'),
('door', 'verb', 'noun', 'Door is a person, place, or thing, so it''s a noun'),
('window', 'adverb', 'noun', 'Window is a person, place, or thing, so it''s a noun'),
('bike', 'adjective', 'noun', 'Bike is a person, place, or thing, so it''s a noun'),
('teacher', 'verb', 'noun', 'Teacher is a person, place, or thing, so it''s a noun'),
('student', 'adverb', 'noun', 'Student is a person, place, or thing, so it''s a noun'),
('friend', 'adjective', 'noun', 'Friend is a person, place, or thing, so it''s a noun'),
('family', 'verb', 'noun', 'Family is a person, place, or thing, so it''s a noun'),
('city', 'adverb', 'noun', 'City is a person, place, or thing, so it''s a noun'),
('country', 'adjective', 'noun', 'Country is a person, place, or thing, so it''s a noun'),
('school', 'verb', 'noun', 'School is a person, place, or thing, so it''s a noun'),
('hospital', 'adverb', 'noun', 'Hospital is a person, place, or thing, so it''s a noun'),
('restaurant', 'adjective', 'noun', 'Restaurant is a person, place, or thing, so it''s a noun'),
('music', 'verb', 'noun', 'Music is a person, place, or thing, so it''s a noun'),
('love', 'adverb', 'noun', 'Love is a person, place, or thing, so it''s a noun'),
('happiness', 'adjective', 'noun', 'Happiness is a person, place, or thing, so it''s a noun'),
('freedom', 'verb', 'noun', 'Freedom is a person, place, or thing, so it''s a noun'),
('knowledge', 'adverb', 'noun', 'Knowledge is a person, place, or thing, so it''s a noun'),

-- VERBS (action words) - mixed incorrect options
('run', 'noun', 'verb', 'Run is an action word, so it''s a verb'),
('jump', 'adjective', 'verb', 'Jump is an action word, so it''s a verb'),
('write', 'adverb', 'verb', 'Write is an action word, so it''s a verb'),
('read', 'noun', 'verb', 'Read is an action word, so it''s a verb'),
('sing', 'adjective', 'verb', 'Sing is an action word, so it''s a verb'),
('dance', 'noun', 'verb', 'Dance is an action word, so it''s a verb'),
('swim', 'adverb', 'verb', 'Swim is an action word, so it''s a verb'),
('walk', 'adjective', 'verb', 'Walk is an action word, so it''s a verb'),
('talk', 'noun', 'verb', 'Talk is an action word, so it''s a verb'),
('eat', 'adverb', 'verb', 'Eat is an action word, so it''s a verb'),
('sleep', 'adjective', 'verb', 'Sleep is an action word, so it''s a verb'),
('laugh', 'noun', 'verb', 'Laugh is an action word, so it''s a verb'),
('cry', 'adverb', 'verb', 'Cry is an action word, so it''s a verb'),
('think', 'adjective', 'verb', 'Think is an action word, so it''s a verb'),
('learn', 'noun', 'verb', 'Learn is an action word, so it''s a verb'),
('teach', 'adverb', 'verb', 'Teach is an action word, so it''s a verb'),
('work', 'adjective', 'verb', 'Work is an action word, so it''s a verb'),
('play', 'noun', 'verb', 'Play is an action word, so it''s a verb'),
('drive', 'adverb', 'verb', 'Drive is an action word, so it''s a verb'),
('fly', 'adjective', 'verb', 'Fly is an action word, so it''s a verb'),
('cook', 'noun', 'verb', 'Cook is an action word, so it''s a verb'),
('clean', 'adverb', 'verb', 'Clean is an action word, so it''s a verb'),
('build', 'adjective', 'verb', 'Build is an action word, so it''s a verb'),
('create', 'noun', 'verb', 'Create is an action word, so it''s a verb'),
('destroy', 'adverb', 'verb', 'Destroy is an action word, so it''s a verb'),
('help', 'adjective', 'verb', 'Help is an action word, so it''s a verb'),

-- ADJECTIVES (describe nouns) - mixed incorrect options
('happy', 'noun', 'adjective', 'Happy describes a person or thing, so it''s an adjective'),
('beautiful', 'verb', 'adjective', 'Beautiful describes a person or thing, so it''s an adjective'),
('smart', 'adverb', 'adjective', 'Smart describes a person or thing, so it''s an adjective'),
('tall', 'noun', 'adjective', 'Tall describes a person or thing, so it''s an adjective'),
('big', 'verb', 'adjective', 'Big describes a person or thing, so it''s an adjective'),
('small', 'noun', 'adjective', 'Small describes a person or thing, so it''s an adjective'),
('fast', 'adverb', 'adjective', 'Fast describes a person or thing, so it''s an adjective'),
('slow', 'noun', 'adjective', 'Slow describes a person or thing, so it''s an adjective'),
('clever', 'verb', 'adjective', 'Clever describes a person or thing, so it''s an adjective'),
('brave', 'adverb', 'adjective', 'Brave describes a person or thing, so it''s an adjective'),
('strong', 'noun', 'adjective', 'Strong describes a person or thing, so it''s an adjective'),
('weak', 'verb', 'adjective', 'Weak describes a person or thing, so it''s an adjective'),
('young', 'noun', 'adjective', 'Young describes a person or thing, so it''s an adjective'),
('old', 'adverb', 'adjective', 'Old describes a person or thing, so it''s an adjective'),
('kind', 'verb', 'adjective', 'Kind describes a person or thing, so it''s an adjective'),
('wise', 'noun', 'adjective', 'Wise describes a person or thing, so it''s an adjective'),
('friendly', 'verb', 'adjective', 'Friendly describes a person or thing, so it''s an adjective'),
('angry', 'noun', 'adjective', 'Angry describes a person or thing, so it''s an adjective'),
('sad', 'adverb', 'adjective', 'Sad describes a person or thing, so it''s an adjective'),
('excited', 'noun', 'adjective', 'Excited describes a person or thing, so it''s an adjective'),
('bored', 'verb', 'adjective', 'Bored describes a person or thing, so it''s an adjective'),
('tired', 'noun', 'adjective', 'Tired describes a person or thing, so it''s an adjective'),
('hungry', 'adverb', 'adjective', 'Hungry describes a person or thing, so it''s an adjective'),
('thirsty', 'noun', 'adjective', 'Thirsty describes a person or thing, so it''s an adjective'),
('clean', 'verb', 'adjective', 'Clean describes a person or thing, so it''s an adjective'),
('dirty', 'adverb', 'adjective', 'Dirty describes a person or thing, so it''s an adjective'),

-- ADVERBS (describe verbs, adjectives, other adverbs) - mixed incorrect options
('quickly', 'noun', 'adverb', 'Quickly describes how an action is done, so it''s an adverb'),
('slowly', 'verb', 'adverb', 'Slowly describes how an action is done, so it''s an adverb'),
('carefully', 'adjective', 'adverb', 'Carefully describes how an action is done, so it''s an adverb'),
('gently', 'noun', 'adverb', 'Gently describes how an action is done, so it''s an adverb'),
('loudly', 'verb', 'adverb', 'Loudly describes how an action is done, so it''s an adverb'),
('quietly', 'adjective', 'adverb', 'Quietly describes how an action is done, so it''s an adverb'),
('softly', 'noun', 'adverb', 'Softly describes how an action is done, so it''s an adverb'),
('easily', 'verb', 'adverb', 'Easily describes how an action is done, so it''s an adverb'),
('hard', 'adjective', 'adverb', 'Hard describes how an action is done, so it''s an adverb'),
('well', 'noun', 'adverb', 'Well describes how an action is done, so it''s an adverb'),
('badly', 'verb', 'adverb', 'Badly describes how an action is done, so it''s an adverb'),
('early', 'adjective', 'adverb', 'Early describes when an action happens, so it''s an adverb'),
('late', 'noun', 'adverb', 'Late describes when an action happens, so it''s an adverb'),
('soon', 'verb', 'adverb', 'Soon describes when an action happens, so it''s an adverb'),
('now', 'adjective', 'adverb', 'Now describes when an action happens, so it''s an adverb'),
('here', 'noun', 'adverb', 'Here describes where an action happens, so it''s an adverb'),
('there', 'verb', 'adverb', 'There describes where an action happens, so it''s an adverb'),
('everywhere', 'adjective', 'adverb', 'Everywhere describes where an action happens, so it''s an adverb'),
('never', 'noun', 'adverb', 'Never describes when an action happens, so it''s an adverb'),
('always', 'verb', 'adverb', 'Always describes when an action happens, so it''s an adverb'),
('sometimes', 'adjective', 'adverb', 'Sometimes describes when an action happens, so it''s an adverb'),
('often', 'noun', 'adverb', 'Often describes when an action happens, so it''s an adverb'),
('rarely', 'verb', 'adverb', 'Rarely describes when an action happens, so it''s an adverb'),
('very', 'noun', 'adverb', 'Very describes how much, so it''s an adverb'),
('really', 'adjective', 'adverb', 'Really describes how much, so it''s an adverb'),
('quite', 'verb', 'adverb', 'Quite describes how much, so it''s an adverb'),

-- MIXED DIFFICULTY - more randomization
('bright', 'noun', 'adjective', 'Bright describes a person or thing, so it''s an adjective'),
('dark', 'verb', 'adjective', 'Dark describes a person or thing, so it''s an adjective'),
('warm', 'adverb', 'adjective', 'Warm describes a person or thing, so it''s an adjective'),
('cold', 'noun', 'adjective', 'Cold describes a person or thing, so it''s an adjective'),
('hot', 'verb', 'adjective', 'Hot describes a person or thing, so it''s an adjective'),
('cool', 'adverb', 'adjective', 'Cool describes a person or thing, so it''s an adjective'),
('wet', 'noun', 'adjective', 'Wet describes a person or thing, so it''s an adjective'),
('dry', 'verb', 'adjective', 'Dry describes a person or thing, so it''s an adjective'),
('new', 'adverb', 'adjective', 'New describes a person or thing, so it''s an adjective'),
('fresh', 'noun', 'adjective', 'Fresh describes a person or thing, so it''s an adjective'),
('sweet', 'verb', 'adjective', 'Sweet describes a person or thing, so it''s an adjective'),
('sour', 'adverb', 'adjective', 'Sour describes a person or thing, so it''s an adjective'),
('bitter', 'noun', 'adjective', 'Bitter describes a person or thing, so it''s an adjective'),
('spicy', 'verb', 'adjective', 'Spicy describes a person or thing, so it''s an adjective'),
('smooth', 'adverb', 'adjective', 'Smooth describes a person or thing, so it''s an adjective'),
('rough', 'noun', 'adjective', 'Rough describes a person or thing, so it''s an adjective'),
('soft', 'verb', 'adjective', 'Soft describes a person or thing, so it''s an adjective'),
('hard', 'adverb', 'adjective', 'Hard describes a person or thing, so it''s an adjective'),
('heavy', 'noun', 'adjective', 'Heavy describes a person or thing, so it''s an adjective'),
('light', 'verb', 'adjective', 'Light describes a person or thing, so it''s an adjective'),
('thick', 'adverb', 'adjective', 'Thick describes a person or thing, so it''s an adjective'),
('thin', 'noun', 'adjective', 'Thin describes a person or thing, so it''s an adjective'),
('wide', 'verb', 'adjective', 'Wide describes a person or thing, so it''s an adjective'),
('narrow', 'adverb', 'adjective', 'Narrow describes a person or thing, so it''s an adjective'),
('long', 'noun', 'adjective', 'Long describes a person or thing, so it''s an adjective'),
('short', 'verb', 'adjective', 'Short describes a person or thing, so it''s an adjective'),

-- MORE VERBS - varied incorrect options
('speak', 'adjective', 'verb', 'Speak is an action word, so it''s a verb'),
('listen', 'noun', 'verb', 'Listen is an action word, so it''s a verb'),
('watch', 'adverb', 'verb', 'Watch is an action word, so it''s a verb'),
('see', 'adjective', 'verb', 'See is an action word, so it''s a verb'),
('hear', 'noun', 'verb', 'Hear is an action word, so it''s a verb'),
('smell', 'adverb', 'verb', 'Smell is an action word, so it''s a verb'),
('touch', 'adjective', 'verb', 'Touch is an action word, so it''s a verb'),
('feel', 'noun', 'verb', 'Feel is an action word, so it''s a verb'),
('taste', 'adverb', 'verb', 'Taste is an action word, so it''s a verb'),
('buy', 'adjective', 'verb', 'Buy is an action word, so it''s a verb'),
('sell', 'noun', 'verb', 'Sell is an action word, so it''s a verb'),
('give', 'adverb', 'verb', 'Give is an action word, so it''s a verb'),
('take', 'adjective', 'verb', 'Take is an action word, so it''s a verb'),
('bring', 'noun', 'verb', 'Bring is an action word, so it''s a verb'),
('carry', 'adverb', 'verb', 'Carry is an action word, so it''s a verb'),
('push', 'adjective', 'verb', 'Push is an action word, so it''s a verb'),
('pull', 'noun', 'verb', 'Pull is an action word, so it''s a verb'),
('lift', 'adverb', 'verb', 'Lift is an action word, so it''s a verb'),
('drop', 'adjective', 'verb', 'Drop is an action word, so it''s a verb'),
('catch', 'noun', 'verb', 'Catch is an action word, so it''s a verb'),
('throw', 'adverb', 'verb', 'Throw is an action word, so it''s a verb'),
('kick', 'adjective', 'verb', 'Kick is an action word, so it''s a verb'),
('hit', 'noun', 'verb', 'Hit is an action word, so it''s a verb'),
('break', 'adverb', 'verb', 'Break is an action word, so it''s a verb'),
('fix', 'adjective', 'verb', 'Fix is an action word, so it''s a verb'),
('open', 'noun', 'verb', 'Open is an action word, so it''s a verb'),
('close', 'adverb', 'verb', 'Close is an action word, so it''s a verb'),

-- MORE NOUNS - varied incorrect options
('dog', 'adjective', 'noun', 'Dog is a person, place, or thing, so it''s a noun'),
('cat', 'verb', 'noun', 'Cat is a person, place, or thing, so it''s a noun'),
('bird', 'adverb', 'noun', 'Bird is a person, place, or thing, so it''s a noun'),
('fish', 'adjective', 'noun', 'Fish is a person, place, or thing, so it''s a noun'),
('horse', 'verb', 'noun', 'Horse is a person, place, or thing, so it''s a noun'),
('cow', 'adverb', 'noun', 'Cow is a person, place, or thing, so it''s a noun'),
('sheep', 'adjective', 'noun', 'Sheep is a person, place, or thing, so it''s a noun'),
('pig', 'verb', 'noun', 'Pig is a person, place, or thing, so it''s a noun'),
('chicken', 'adverb', 'noun', 'Chicken is a person, place, or thing, so it''s a noun'),
('duck', 'adjective', 'noun', 'Duck is a person, place, or thing, so it''s a noun'),
('elephant', 'verb', 'noun', 'Elephant is a person, place, or thing, so it''s a noun'),
('tiger', 'adverb', 'noun', 'Tiger is a person, place, or thing, so it''s a noun'),
('lion', 'adjective', 'noun', 'Lion is a person, place, or thing, so it''s a noun'),
('bear', 'verb', 'noun', 'Bear is a person, place, or thing, so it''s a noun'),
('wolf', 'adverb', 'noun', 'Wolf is a person, place, or thing, so it''s a noun'),
('fox', 'adjective', 'noun', 'Fox is a person, place, or thing, so it''s a noun'),
('rabbit', 'verb', 'noun', 'Rabbit is a person, place, or thing, so it''s a noun'),
('deer', 'adverb', 'noun', 'Deer is a person, place, or thing, so it''s a noun'),
('monkey', 'adjective', 'noun', 'Monkey is a person, place, or thing, so it''s a noun'),
('snake', 'verb', 'noun', 'Snake is a person, place, or thing, so it''s a noun'),
('frog', 'adverb', 'noun', 'Frog is a person, place, or thing, so it''s a noun'),
('butterfly', 'adjective', 'noun', 'Butterfly is a person, place, or thing, so it''s a noun'),
('bee', 'verb', 'noun', 'Bee is a person, place, or thing, so it''s a noun'),
('spider', 'adverb', 'noun', 'Spider is a person, place, or thing, so it''s a noun'),
('ant', 'adjective', 'noun', 'Ant is a person, place, or thing, so it''s a noun'),
('fly', 'verb', 'noun', 'Fly is a person, place, or thing, so it''s a noun'),
('mosquito', 'adverb', 'noun', 'Mosquito is a person, place, or thing, so it''s a noun'),

-- MORE ADJECTIVES - varied incorrect options
('brave', 'noun', 'adjective', 'Brave describes a person or thing, so it''s an adjective'),
('scared', 'verb', 'adjective', 'Scared describes a person or thing, so it''s an adjective'),
('confident', 'adverb', 'adjective', 'Confident describes a person or thing, so it''s an adjective'),
('shy', 'noun', 'adjective', 'Shy describes a person or thing, so it''s an adjective'),
('proud', 'verb', 'adjective', 'Proud describes a person or thing, so it''s an adjective'),
('humble', 'adverb', 'adjective', 'Humble describes a person or thing, so it''s an adjective'),
('generous', 'noun', 'adjective', 'Generous describes a person or thing, so it''s an adjective'),
('selfish', 'verb', 'adjective', 'Selfish describes a person or thing, so it''s an adjective'),
('honest', 'adverb', 'adjective', 'Honest describes a person or thing, so it''s an adjective'),
('dishonest', 'noun', 'adjective', 'Dishonest describes a person or thing, so it''s an adjective'),
('loyal', 'verb', 'adjective', 'Loyal describes a person or thing, so it''s an adjective'),
('faithful', 'adverb', 'adjective', 'Faithful describes a person or thing, so it''s an adjective'),
('patient', 'noun', 'adjective', 'Patient describes a person or thing, so it''s an adjective'),
('impatient', 'verb', 'adjective', 'Impatient describes a person or thing, so it''s an adjective'),
('polite', 'adverb', 'adjective', 'Polite describes a person or thing, so it''s an adjective'),
('rude', 'noun', 'adjective', 'Rude describes a person or thing, so it''s an adjective'),
('funny', 'verb', 'adjective', 'Funny describes a person or thing, so it''s an adjective'),
('serious', 'adverb', 'adjective', 'Serious describes a person or thing, so it''s an adjective'),
('creative', 'noun', 'adjective', 'Creative describes a person or thing, so it''s an adjective'),
('artistic', 'verb', 'adjective', 'Artistic describes a person or thing, so it''s an adjective'),
('musical', 'adverb', 'adjective', 'Musical describes a person or thing, so it''s an adjective'),
('athletic', 'noun', 'adjective', 'Athletic describes a person or thing, so it''s an adjective'),
('intelligent', 'verb', 'adjective', 'Intelligent describes a person or thing, so it''s an adjective'),
('stupid', 'adverb', 'adjective', 'Stupid describes a person or thing, so it''s an adjective'),
('lazy', 'noun', 'adjective', 'Lazy describes a person or thing, so it''s an adjective'),
('hardworking', 'verb', 'adjective', 'Hardworking describes a person or thing, so it''s an adjective'),
('curious', 'adverb', 'adjective', 'Curious describes a person or thing, so it''s an adjective'),

-- MORE ADVERBS - varied incorrect options
('suddenly', 'noun', 'adverb', 'Suddenly describes when an action happens, so it''s an adverb'),
('gradually', 'verb', 'adverb', 'Gradually describes how an action happens, so it''s an adverb'),
('immediately', 'adjective', 'adverb', 'Immediately describes when an action happens, so it''s an adverb'),
('eventually', 'noun', 'adverb', 'Eventually describes when an action happens, so it''s an adverb'),
('finally', 'verb', 'adverb', 'Finally describes when an action happens, so it''s an adverb'),
('recently', 'adjective', 'adverb', 'Recently describes when an action happens, so it''s an adverb'),
('yesterday', 'noun', 'adverb', 'Yesterday describes when an action happens, so it''s an adverb'),
('tomorrow', 'verb', 'adverb', 'Tomorrow describes when an action happens, so it''s an adverb'),
('today', 'adjective', 'adverb', 'Today describes when an action happens, so it''s an adverb'),
('tonight', 'noun', 'adverb', 'Tonight describes when an action happens, so it''s an adverb'),
('inside', 'verb', 'adverb', 'Inside describes where an action happens, so it''s an adverb'),
('outside', 'adjective', 'adverb', 'Outside describes where an action happens, so it''s an adverb'),
('upstairs', 'noun', 'adverb', 'Upstairs describes where an action happens, so it''s an adverb'),
('downstairs', 'verb', 'adverb', 'Downstairs describes where an action happens, so it''s an adverb'),
('upward', 'adjective', 'adverb', 'Upward describes direction, so it''s an adverb'),
('downward', 'noun', 'adverb', 'Downward describes direction, so it''s an adverb'),
('forward', 'verb', 'adverb', 'Forward describes direction, so it''s an adverb'),
('backward', 'adjective', 'adverb', 'Backward describes direction, so it''s an adverb'),
('sideways', 'noun', 'adverb', 'Sideways describes direction, so it''s an adverb'),
('straight', 'verb', 'adverb', 'Straight describes direction, so it''s an adverb'),
('together', 'adjective', 'adverb', 'Together describes how an action happens, so it''s an adverb'),
('separately', 'noun', 'adverb', 'Separately describes how an action happens, so it''s an adverb'),
('alone', 'verb', 'adverb', 'Alone describes how an action happens, so it''s an adverb'),
('apart', 'adjective', 'adverb', 'Apart describes how an action happens, so it''s an adverb'),
('nearby', 'noun', 'adverb', 'Nearby describes where an action happens, so it''s an adverb'),
('far', 'verb', 'adverb', 'Far describes where an action happens, so it''s an adverb'); 